module.exports = {
    title: 'react-ui-tree',
    children: [{
        title: 'sdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf',
        tips: 'sdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf',
        leaf: false,
        children: [{
            title: '数据库的房价开始，数据库两地分居数据库两地分居',
            leaf: false
        }, {
            title: 'react-ui-tree.cssreact-ui-tree.cssreact-ui-tree.cssreact-ui-tree.css',
            leaf: false
        }, {
            title: 'react-ui-tree.js',
            leaf: false
        }, {
            title: 'tree.js',
            leaf: false
        }]
    }, {
        title: 'example',
        leaf: false,
        children: [{
            title: 'app.js',
            leaf: false
        }, {
            title: 'app.less',
            leaf: false
        }, {
            title: 'index.html',
            leaf: false
        }]
    }, {
        title: 'lib',
        leaf: false,
        children: [{
            title: 'node.js',
            leaf: false
        }, {
            title: 'react-ui-tree.js',
            leaf: false
        }, {
            title: 'react-ui-tree.less',
            leaf: false
        }, {
            title: 'tree.js',
            leaf: false
        }]
    }, {
        title: '.gitiignore',
        leaf: false
    }, {
        title: 'index.js',
        leaf: false
    }, {
        title: 'LICENSE',
        leaf: false
    }, {
        title: 'Makefile',
        leaf: false
    }, {
        title: 'package.json',
        leaf: false
    }, {
        title: 'README.md',
        leaf: false
    }, {
        title: 'webpack.config.js',
        leaf: false
    }]
}
